"""add_user_knowledge

Revision ID: 234c8e308a65
Revises: 19a4188dd87d
Create Date: 2026-06-02 06:26:01.753934

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '234c8e308a65'
down_revision: Union[str, Sequence[str], None] = '19a4188dd87d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_knowledge',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_knowledge_id'), 'user_knowledge', ['id'], unique=False)
    op.create_index(op.f('ix_user_knowledge_user_id'), 'user_knowledge', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_knowledge_user_id'), table_name='user_knowledge')
    op.drop_index(op.f('ix_user_knowledge_id'), table_name='user_knowledge')
    op.drop_table('user_knowledge')
    # ### end Alembic commands ###
