"""add_health_connect_syncs

Revision ID: 5f19570994b2
Revises: da60d2b93599
Create Date: 2026-06-02 14:11:53.916939

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5f19570994b2'
down_revision: Union[str, Sequence[str], None] = 'da60d2b93599'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('health_connect_syncs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('synced_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('steps', sa.Integer(), nullable=True),
    sa.Column('resting_heart_rate', sa.Float(), nullable=True),
    sa.Column('hrv_rmssd', sa.Float(), nullable=True),
    sa.Column('sleep_duration_minutes', sa.Integer(), nullable=True),
    sa.Column('sleep_score', sa.Integer(), nullable=True),
    sa.Column('deep_sleep_minutes', sa.Integer(), nullable=True),
    sa.Column('rem_sleep_minutes', sa.Integer(), nullable=True),
    sa.Column('light_sleep_minutes', sa.Integer(), nullable=True),
    sa.Column('active_calories', sa.Integer(), nullable=True),
    sa.Column('distance_meters', sa.Integer(), nullable=True),
    sa.Column('oxygen_saturation', sa.Float(), nullable=True),
    sa.Column('respiratory_rate', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'date', name='uq_hc_user_date')
    )
    op.create_index(op.f('ix_health_connect_syncs_id'), 'health_connect_syncs', ['id'], unique=False)
    op.create_index(op.f('ix_health_connect_syncs_user_id'), 'health_connect_syncs', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_health_connect_syncs_user_id'), table_name='health_connect_syncs')
    op.drop_index(op.f('ix_health_connect_syncs_id'), table_name='health_connect_syncs')
    op.drop_table('health_connect_syncs')
    # ### end Alembic commands ###
