"""add_daily_check_ins

Revision ID: 98254bcf8e47
Revises: 234c8e308a65
Create Date: 2026-06-02 07:53:16.504424

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '98254bcf8e47'
down_revision: Union[str, Sequence[str], None] = '234c8e308a65'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('daily_check_ins',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('sleep_quality', sa.Integer(), nullable=False),
    sa.Column('fatigue', sa.Integer(), nullable=False),
    sa.Column('shoulder_pain', sa.Integer(), nullable=False),
    sa.Column('motivation', sa.Integer(), nullable=False),
    sa.Column('rugby_session_yesterday', sa.Boolean(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'date', name='uq_user_checkin_date')
    )
    op.create_index(op.f('ix_daily_check_ins_id'), 'daily_check_ins', ['id'], unique=False)
    op.create_index(op.f('ix_daily_check_ins_user_id'), 'daily_check_ins', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_daily_check_ins_user_id'), table_name='daily_check_ins')
    op.drop_index(op.f('ix_daily_check_ins_id'), table_name='daily_check_ins')
    op.drop_table('daily_check_ins')
    # ### end Alembic commands ###
