"""add_readiness_score_to_checkins

Revision ID: da60d2b93599
Revises: 98254bcf8e47
Create Date: 2026-06-02 07:57:45.139052

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'da60d2b93599'
down_revision: Union[str, Sequence[str], None] = '98254bcf8e47'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('daily_check_ins', sa.Column('readiness_score', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('daily_check_ins', 'readiness_score')
    # ### end Alembic commands ###
